### ISSUE TITLE
Creation of GeoDataFrames.jl?

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/meta#2]
I have written a simple wrapper for GeoDataFrames that I think would be useful to others not necessarily interested in Geostatistics: https://github.com/juliohm/GeoStats.jl/blob/master/src/geodataframe.jl. I was thinking of creating a lightweight package for it in the JuliaGeo organization, but I would like to ask you about your thoughts?

Please let me know if I can help.

**Comment by yeesian** [comment]
I agree it'll be nice to have a GeoDataFrames package, and I have [played around with the idea](https://github.com/yeesian/GeoDataFrames.jl) before.

It's not clear to me what it is about the wrapper you wrote that makes it spatial/"geo" though; e.g. why not work with vanilla DataFrames? Is the intended usecase for it to eventually be able to work with map projections, and other geometries and operations like in [geopandas](https://github.com/geopandas/geopandas)?

**Comment by juliohm** [comment]
Hi @yeesian, my original idea with GeoDataFrames is that it is only a lightweight wrapper over a DataFrame storing metadata about the coordinate columns. Later on, one could have more refined "spatial/geo" types for the columns as soon as they become standard in the JuliaGeo organization.

I like this approach because it saves us from re-implementing functionality available in DataFrames.jl and also makes the usage straightforward. Users don't need to learn a new API, and we can just *extend* it with more functions that handle the "spatial" aspect of the data. I think some R packages for spatial data do exactly this.

If you know a reason for implementing more than a lightweight wrapper, I'd be happy to learn about it. I will create the repository in the organization and we can evolve the ideas there :+1:

**Comment by juliohm** [comment]
Or you can create the repository yourself :blush: , I don't have enough permissions.

**Comment by juliohm** [comment]
I have permission now, thank you. We can continue the discussion in the repository: https://github.com/JuliaGeo/GeoDataFrames.jl

**Comment by yeesian** [comment]
Sorry I was unclear earlier: while I like the idea of having a `JuliaGeo/GeoDataFrames` package, it doesn't mean it makes sense to have one yet. It's not even clear what (geospatial) interface is meant to be satisfied by such a package, and I think it's pre-mature to commit ourselves to one under JuliaGeo. Is there a reason why such a package shouldn't be developed separately elsewhere first?

**Comment by juliohm** [comment]
Hi @yeesian, I misinterpreted your comments, sorry. Why wouldn't JuliaGeo be a good place for the package? Isn't the organization for geospatial-related packages?

You mean the GeoInterface.jl package is not related? Is that an issue?

**Comment by yeesian** [comment]
> Why wouldn't JuliaGeo be a good place for the package?

The priority of the organization is to provide a mature and stable set of functionality for other developers to build upon. Because the organization lacks a core of active volunteers for developing packages, it is currently sustainable for maintenance of wrappers around important C libraries that are commonly used in geospatial applications, but not for actively developing packages.

> If you know a reason for implementing more than a lightweight wrapper, I'd be happy to learn about it.

Analogous packages in Python ([geopandas](https://github.com/geopandas/geopandas)) and R ([spatial* dataframes](https://cran.r-project.org/web/packages/sp/vignettes/intro_sp.pdf)) have typically worked well with GDAL and GEOS because they provide functionality ([e.g. spatial joins, etc](https://github.com/geopandas/geopandas/wiki/Notebooks)) that you would come to expect from such an object, and should have a [similar user experience as working with geospatial databases](https://yeesian.github.io/maptime-boston-julia/#/4/1) (e.g. using PostGIS and/or Spatialite).

> it is only a lightweight wrapper over a DataFrame storing metadata about the coordinate columns. [...] Users don't need to learn a new API, and we can just extend it with more functions that handle the "spatial" aspect of the data. I think some R packages for spatial data do exactly this.

I haven't yet seen any proposals for a geodataframe API in this thread, since there is nothing inherently geospatial about wrappers that store metadata over a DataFrame: is there a reason why such functionality wouldn't be better e.g. in the JuliaData organization?

> Later on, one could have more refined "spatial/geo" types for the columns as soon as they become standard in the JuliaGeo organization.

That's the proposal/work that needs to be completed satisfactorily, before we commit to developing and maintaining the package at an organizational level. [The last time it was brought up](https://github.com/JuliaGeometry/meta/wiki/First-Meetup-Minutes), there wasn't sufficient consensus on an appropriate object model, so what are these refined "spatial/geo" types you speak of?

**Comment by juliohm** [comment]
I see, this is definitely a lot of work ahead and I am looking forward to see it happening. I don't have the time to work on these features myself though, at least at this point, but I will try to read more about it.

Meanwhile, I can delete the repository from JuliaGeo and wait/work for/on a good proposal. I think JuliaGeo is a better fit to GeoDataFrames than JuliaData, but that is subjective. I will delete the repository by the end of the day unless someone disagrees with the deletion.

**Comment by yeesian** [comment]
I really appreciate your patience and understanding in opening this issue to ask, thanks! (:

I too lack the time to work on them in the near future, and am sorry these considerations have not been very well-documented.

**Comment by juliohm** [comment]
Thank you @yeesian, I am closing this issue, looking forward to discuss more.
