### ISSUE TITLE
Better organizing the JuliaGeo efforts

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/meta#9]
Based on the [how to create a leaner ecosystem](https://discourse.julialang.org/t/how-can-we-create-a-leaner-ecosystem-for-julia/32904) discussion on Discourse, I think it would be beneficial for our organization if we could make more explicit somehow the main authors/maintainers of packages that are part of the organization. I see that we discuss some of these details in our Wiki pages [here](https://github.com/JuliaGeo/meta/blob/master/GettingInvolved.md#register-your-package-under-the-juliageo-organization) but that doesn't seem to preserve the power of the author/creator of the package to decide what is aligned with his/her original vision for the project, and what can be merged into the packages. I suggest that we brainstorm a guideline for acknowledging the leading author(s) for each package in the organization in a way that org members understand that this same authors will have the final word about proposed code changes. If we can achieve such guideline where contributors need to contact the leading authors before merging PRs, I think the organization will become a safe environment for more packages in the ecosystem. I am particularly considering moving the [GeoStats.jl stack](https://github.com/juliohm/GeoStats.jl#project-organization) to JuliaGeo if that is seen as something useful here.

On a related topic, I think we need to review the current packages under the JuliaGeo umbrella, and update our Wiki pages or website to reflect which packages are maintained still and who are the leading authors. I personally think that the website should be the central point of communication and updates, and that our Wiki pages on GitHub could be moved therein. Particularly, we need to update the [existing libraries page](https://github.com/JuliaGeo/meta/wiki/Existing-Libraries) and migrate it to the website if it is not there yet.

Could you please share your thoughts on how we could proceed? Can we start by archiving dead projects or projects that authors don't have the intent to maintain and update? After we have a cleaned list of packages that are maintained, we can start brainstorming overlaping features, and mapping what features are missing the JuliaGeo ecosystem.

I appreciate your input on these issues, and I am looking forward to discussing them more.

**Comment by juliohm** [comment]
Also do we have guidelines for the functions of each member in the organization? Unlike other organizations which I am part of like JuliaImages, the JuliaGeo organization has too many owners as opposed to members. Ownerwship of organizations could also be discussed here because they give too much power to the person in the organization.

I wonder if we can have a contributorship file stating the reasons for why each person was added to the org. Contributorship is a concept that is becoming popular in journals, and I think we will hardly improve the status quo without considering it carefully: https://www.mdpi.com/2304-6775/7/3/48/htm

**Comment by visr** [comment]
Thanks for raising some of these points Júlio. Perhaps "Better organizing the JuliaGeo efforts" is a bit of a broad issue in a repo "For discussion centered around the JuliaGeo organization" ;)

I'll comment on a few points:

I think it may be good to explicitly mention the authors and current maintainers for the different packages. Note that these are not always the same person. I can understand your point about authors having the final word, and believe that in practice this already happens, but it's fine to make it more explicit.

Regarding the website, I agree that we should move the wiki pages to the website, it will probably be more visible there. There is a more recent existing libraries page already on the site, but it would be nice to update and expand it.

Which projects were you thinking about to archive dead projects? I don't see any under JuliaGeo.

Regarding JuliaGeo owners, I agree there are too many, there should probably be only a few. If you are one now and don't think you need to be, let us know and we can make you a regular member (doesn't seem like you can do it yourself). The main reason I think we have so many owners is because people need to be owner to move stuff in. But for this we should probably only make them a temporary owner. And perhaps we can make better use of the Teams feature. The other reason is probably because by now the majority is owner, it seems more in line with the rest... Probably a more pressing concern though is people not having [2FA](https://help.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa) enabled. Especially in combination with being an owner this is dangerous. So if you read this and don't have 2FA enabled, please do so now! We could move toward [requiring two-factor authentication](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization) in JuliaGeo in the future.

**Comment by juliohm** [comment]
> Which projects were you thinking about to archive dead projects? I don't see any under JuliaGeo.

Thank you @visr , I don't have any specific project in mind, just saw some packages with little activity or packages that seemed redundant at a first glance.

> If you are one now and don't think you need to be, let us know and we can make you a regular member (doesn't seem like you can do it yourself). The main reason I think we have so many owners is because people need to be owner to move stuff in. But for this we should probably only make them a temporary owner.

So only owners can move packages to the org? I understand why there are so many now. I agree this should be a temporary feature. Also, GitHub Teams are a great idea.

> Probably a more pressing concern though is people not having [2FA](https://help.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa) enabled. Especially in combination with being an owner this is dangerous.

I fully agree. I got scared when I saw so many people without 2FA in the organization.

**Comment by visr** [comment]
I've messaged people asking to enable 2FA. We should be able to enforce it quite soon.

> I am particularly considering moving the GeoStats.jl stack to JuliaGeo if that is seen as something useful here.

Since there has been some discussion on scope recently in various threads, I attempted to summarize and clarify if now on https://juliageo.org/, see the "GitHub organizations" header. Geostatistics is particularly interesting, because it can both be seen as generally useful to other geoscience domains, as well as its own domain. So something could be said for moving it here, and for creating a geostatistics domain org. I'm fine with either. To control the rights better, we should probably set up a geostats team, and move away from the current single team setup.

**Comment by visr** [comment]
Everybody now enabled 2FA, so I just made it a organization requirement in the settings. Thanks all!

Regarding the move of the GeoStats stack. Júlio created JuliaEarth and moved it in there. To prevent overlap between the two organisations, I now think it's best to focus on geospatial tools in this GitHub organization. JuliaEarth will focus on geoscience instead.

There are many issues raised here, but for further discussion on those it may be better to open dedicated issues.

**Comment by evetion** [comment]
I agree with many of these points, thank you for taking time to write them down. So from @juliohm points and some added:
- [ ] Create a contributors (as in https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) for packages and the org #22 
- [ ] In the above, clearly define the role of the package owner, if any. Júlio can you weigh in about the research aspect of this, if any? Maybe create a citation (https://github.com/citation-file-format/citation-file-format) file as well?
- [ ] Further migrate wiki to site and deprecate wiki. #21
- [x] Enable 2FA for at least all owners
- [x] Archive all dead/non-maintained packages, although I think these are only the builders if we move to JuliaPackaging/Yggdrasil
- [ ] Clean up owners and create teams, but this does require much care to get right

**Comment by visr** [comment]
Good to have a clear list. Anyone, feel free to pick up something if you want.

Regarding 2FA, it is currently already enforced for everyone, not just the owners (only option).

And archiving projects is not really a TODO since there is nothing to archive at the moment. But yes, once we've switched over the other builders to Yggdrasil, we should archive them too.

**Comment by yeesian** [comment]
> Further migrate wiki to site and deprecate wiki.

I'm checking the box for migrating from the wiki, since it's been done in https://github.com/JuliaGeo/meta/pull/11 and subsequent PRs. Let me know if there's anything else to be done for it.

**Comment by visr** [comment]
@yeesian that PR moved things from the wiki to files in the meta repo. Already an improvement, but I was thinking about moving it to juliageo.org.
